---
# defaults file for grav
grav_app_path: "/var/www/grav"
grav_user_path: "/var/www/grav/user"

grav_owner: www-data
# grav_group: www-data

grav_dest: /var/www
grav_webserver_port: 80

grav_domain: 127.0.0.1
grav_letsencrypt_email: false

grav_docker: false

grav_dev: false
grav_sass_service: true
grav_sass_src: false
grav_sass_poll: false

# not used for now
# use_supervisord: yes
# grav_change_user_dir_group_permissions: no
# grav_webserver_user: www-data
